Feature list realization
VlaPol/TMS_Lesson_18 pull request #1
Opened 2023-03-04 15:51 UTC by VlaPol

2023-03-16 18:47 UTC, oleg-grigorijan requested changes

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        lastElement = firstElement;
Можно перенести дальше в else часть. При firstElement == null эта переменная не нужна

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        lastElement = firstElement;
Значение firstElement после выполнения этого метода для остального кода не имеет значения. Твой firstElement может быть локальной переменной

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        int listSize = size();
Неэффективно: сначала size пройдётся по всем элементам в цикле, а потом в схожем цикле мы будем искать элемент по индексу. Можно это сделать за один цикл: тот, что ниже в этом методе. На каждой итерации ещё и проверять выход за длину списка

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +            returnedElement = lastElement.getElement();
Можем это выполнить один раз после цикла

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        int listSize = size();
Тот же комментарий, что и в int get(int index). Большая часть кода в двух методах в итоге будет одинаковая. Создай private метод IntLinkedNode getNode(int index), который возвращает узел по индексу или падает при выходе за пределы списка. Используй его в этих методах

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        int listSize = size();
Неэффективно использовать лишний раз size()

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        for (int i = 0; i < listSize; i++) {
Без size можем итерироваться через lastElement = lastElement.getNextNode() c признаком конца списка lastElement == null

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +    }
Методы для вывода на консоль обычно не создают. Вызывающая сторона просто берёт toString() от объекта и выводит результат

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        return String.valueOf(firstElement);
Выведет только нулевой элемент

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        int listSize = size();
Неэффективно использовать лишний раз size()

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        if (firstElement == lastElement) {
А что мы здесь ждём в lastElement? Там может храниться что угодно в зависимости от того, какие методы вызывались перед remove(int)

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +            lastElement = lastElement.getNextNode();
Не понимаю, зачем тебе тут эти манипуляции с lastElement, который ты обычно используешь для итерирования по списку. Какой тогда смысл ты вложил в lastElement. Что он должен хранить, почему вынесен в поле класса? Скорее всего, твой lastElement должен быть локальными переменными, а тут в принципе не нужен

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +            firstElement = lastElement;
Непоследовательно используешь суффиксы в именах переменных. То "element" у тебя для хранения int элемента, то для хранения Node. То для хранения int элемента используешь "digit". То для хранения Node используешь "node"

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +            if (i + 1 == index) {
По идее ты можешь избавиться от if с break'ом, изменив условие в for. А вообще если сделаешь Node getNode(int index), то сможешь воспользоваться им

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/listrealization/LinkedListRealization.java
> +public class LinkedListRealization {
Как слово реализация на английском используют implementation. Но вообще реализация связного списка – это и есть LinkedList. Довольно путающий нейминг

2023-03-16 18:47 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/listrealization/LinkedListRealization.java
Интереснее было бы увидеть демонстрацию, где создаётся два объекта IntLinkedList и IntArrayList. Действия применяются одновременно к обоим. От обоих должен быть один результат, оба должны иметь одни и те же элементы. Но в целом можешь оставить и так

2023-03-16 18:56 UTC, VlaPol commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        lastElement = firstElement;
да, я это понял из телеграма, я писал что этот момент подправил

2023-03-16 19:13 UTC, VlaPol commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +            returnedElement = lastElement.getElement();
ту не понятно. если вынести returnedElement = lastElement.getElement();  за цикл, то я буду на одну ноду дальше

2023-03-16 19:19 UTC, VlaPol commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +            returnedElement = lastElement.getElement();
Хотя, если цикл изменить, то ок будет

2023-03-16 19:21 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        lastElement = firstElement;
Ой, только не firstElement, а lastElement

2023-03-16 19:38 UTC, VlaPol commented on src/by/tms/lesson18/homework/listrealization/LinkedListRealization.java
> +public class LinkedListRealization {
подправил

2023-03-16 19:51 UTC, VlaPol commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +            lastElement = lastElement.getNextNode();
со второй нодой понятно.

2023-03-19 09:03 UTC, merged

2023-03-19 09:42 UTC, grigo-oleg commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        }
Ошибка не в том, что список пустой, а что index out of bounds. То есть по-хорошему эти две ситуации не должны давать разные исключения

2023-03-19 09:42 UTC, grigo-oleg commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        int deletedElement;
Объявляем переменные максимально близко к использованию

2023-03-19 09:42 UTC, grigo-oleg commented on src/by/tms/lesson18/homework/IntLinkedList.java
> +        int listSize = size();
Не исправил. Напиши без использования size(), то есть без лишнего цикла

2023-03-19 09:42 UTC, grigo-oleg commented on src/by/tms/lesson18/homework/IntList.java
Автоформатирование

2023-03-19 09:42 UTC, grigo-oleg commented on src/by/tms/lesson18/homework/listrealization/LinkedListIterator.java
> +        return null;
У Iterator в документации next() прописан контракт, что должно происходить при вызове метода, когда больше нет элементов. 
А твоя реализация к тому же нарушает принцип fail fast

2023-03-19 09:42 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/listrealization/ArrayListIterator.java
> +        return list.get(index - 1);
У Iterator в документации next() прописан контракт, что должно происходить при вызове метода, когда больше нет элементов.

2023-03-19 09:42 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/listrealization/ArrayListIterator.java
> +        while (size > index) {
Зачем здесь цикл, если мы возвращаемся на первой итерации? Это if

2023-03-19 09:42 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/listrealization/ArrayListIterator.java
> +            index++;
hasNext() не меняет позицию курсора. Позицию курсора меняет next(). Повторный вызов hasNext() без вызова next() должен возвращать тот же результат

2023-03-19 09:42 UTC, oleg-grigorijan commented on src/by/tms/lesson18/homework/listrealization/LinkedList.java
> +                }
Ещё обход через for-each забыл